AdfUIComponents.createComponentClass("AdfRichShowDetailItem",{componentType:"oracle.adf.RichShowDetailItem",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"persist",type:"Array"},{name:"dontPersist",type:"Array"},{name:"badge",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"depressedIcon",type:"String"},{name:"hoverIcon",
type:"String"},{name:"disabledIcon",type:"String"},{name:"icon",type:"String"},{name:"iconDelivery",type:"String","default":"auto"},{name:"text",type:"String"},{name:"accessKey",type:"String"},{name:"flex",type:"Number","default":0},{name:"inflexibleHeight",type:"Number","default":100},{name:"stretchChildren",type:"String","default":"none"},"itemListener",{name:"displayIndex",type:"Number","default":-1},{name:"remove",type:"String","default":"inherit"},{name:"disclosedTransient",type:"Boolean","default":!1}],
eventNames:["item"],superclass:AdfUIShowDetail});
AdfRichUIPeer.createPeerClass(AdfDhtmlShowDisclosurePeer,"AdfDhtmlShowDetailItemPeer");AdfDhtmlShowDetailItemPeer.InitSubclass=function(){AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichShowDetailItem.FLEX,AdfRichShowDetailItem.INFLEXIBLE_HEIGHT)};
AdfDhtmlShowDetailItemPeer.prototype.InitDomElement=function(a,b){AdfDhtmlShowDetailItemPeer.superclass.InitDomElement.call(this,a,b);if("first"==a.getStretchChildren()){var d=AdfDomUtils.getOnlyChildElement(b);if(d&&this._isCapableOfAbsolutePositioning(a,d)){var e=d.style;e.position="absolute";"IFRAME"==d.tagName?(e.width="100%",e.height="100%"):(e.width="auto",e.height="auto",e.top="0px",e.bottom="0px",e.left="0px",e.right="0px")}}else if(AdfAgent.AGENT.getPlatform()==AdfAgent.IE_PLATFORM&&(d=AdfDomUtils.getOnlyChildElement(b))&&
(d.style&&"100%"==d.style.height)&&this._isCapableOfAbsolutePositioning(a,d))d.style.position="absolute"};
AdfDhtmlShowDetailItemPeer.prototype._isCapableOfAbsolutePositioning=function(a,b){var d=b.parentNode;if(window.AdfRichPanelTabbed&&a.getParent()instanceof AdfRichPanelTabbed){for(var e=1,d=b.parentNode;4>e&&null!=d;)d=d.parentNode,null!=d&&++e;if(4==e&&null!=d&&"TD"==d.tagName)return this._bypassStretching=!0,!1}else if(window.AdfRichPanelAccordion&&a.getParent()instanceof AdfRichPanelAccordion){if("absolute"!=d.style.position)return this._bypassStretching=!0,!1}else if(window.AdfRichPanelSpringboard&&
a.getParent()instanceof AdfRichPanelSpringboard&&"absolute"!=d.style.position)return this._bypassStretching=!0,!1;return!0};AdfDhtmlShowDetailItemPeer.prototype.SetBusy=function(a){if(!AdfPage.PAGE.isAttachmentMode()){var b=this.getComponent(),d=b.getParent();d&&"oracle.adf.RichPanelTabbed"==d.getComponentType()&&(b=b.getClientId(),this._changeCursor(b,AdfDhtmlPanelTabbedPeer.TAB_SUB_ID_ABOVE,a),this._changeCursor(b,AdfDhtmlPanelTabbedPeer.TAB_SUB_ID_BELOW,a))}};
AdfDhtmlShowDetailItemPeer.prototype.ComponentFlexChanged=function(a,b,d,e){return this._propertyChangedHandled(a)};AdfDhtmlShowDetailItemPeer.prototype._propertyChangedHandled=function(a){return a.ResizeHandlePropertyChange?!0:!1};AdfDhtmlShowDetailItemPeer.prototype.ComponentInflexibleHeightChanged=function(a,b,d,e){return this._propertyChangedHandled(a)};
AdfDhtmlShowDetailItemPeer.prototype.DomReplaceNotify=function(a){if(!this._bypassStretching){var b=this.getComponent();if("absolute"!=a.style.position&&"absolute"==a.parentNode.style.position)if("first"==b.getStretchChildren())AdfDomUtils.getOnlyChildElement(this.getDomElement())==a&&(b=a.style,b.position="absolute",b.width="100%",b.height="100%");else if(AdfAgent.AGENT.getPlatform()==AdfAgent.IE_PLATFORM){var d=AdfDomUtils.getOnlyChildElement(this.getDomElement());d&&(d==a&&d.style&&"100%"==d.style.height)&&
this._isCapableOfAbsolutePositioning(b,d)&&(d.style.position="absolute")}return a}};AdfDhtmlShowDetailItemPeer.prototype._changeCursor=function(a,b,d){a=AdfRichUIPeer.CreateSubId(a,b);(a=AdfAgent.getAgent().getElementById(a))&&AdfDomUtils.addOrRemoveCSSClassName(d,a,AdfRichUIPeer.BUSY_STYLECLASS)};AdfDhtmlShowDetailItemPeer.prototype.getContainerId=function(a){var b=this.getComponent(),d=b.getParent(),e=d.getPeer();return e&&e.getContainerId?(e.bind(d),e.getContainerId(a)):b.getClientId()};